cmake_minimum_required(VERSION 3.22)
project(stm_flash C)

option(STM_FLASH_LINK_CUBEMX "Link stm32cubemx target automatically" ON)
add_library(stm_flash STATIC stm_flash.c)
target_compile_features(stm_flash PUBLIC c_std_11)
target_include_directories(stm_flash PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
if(STM_FLASH_LINK_CUBEMX AND TARGET stm32cubemx)
    target_link_libraries(stm_flash PUBLIC stm32cubemx)
endif()

if(NOT TARGET stm_common)
    if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/../stm_common/CMakeLists.txt")
        add_subdirectory("${CMAKE_CURRENT_SOURCE_DIR}/../stm_common" "${CMAKE_CURRENT_BINARY_DIR}/stm_common")
    else()
        message(FATAL_ERROR "Provide the stm_common target before adding this component")
    endif()
endif()
target_link_libraries(stm_flash PUBLIC stm_common)
