cmake_minimum_required(VERSION 3.22)
project(stm_flash_portable_tests C CXX)
enable_testing()
add_subdirectory(../.. component)
add_executable(flash_portable test_core.c headers.cpp)
target_link_libraries(flash_portable PRIVATE stm_flash)
target_compile_features(flash_portable PRIVATE c_std_11 cxx_std_17)
if(CMAKE_C_COMPILER_ID MATCHES "GNU|Clang")
    target_compile_options(stm_flash PRIVATE -Wall -Wextra -Werror)
    target_compile_options(flash_portable PRIVATE -Wall -Wextra -Werror)
endif()
add_test(NAME flash_portable COMMAND flash_portable)
